export const palette = {
  // SYSTEM
  systemBlack: '#1A1A1A',
  systemWhite: '#FFFFFF',
  alert: '#CD0000',
  warning: '#FCAF17',
  success: '#118847',
  link: '#0066cc',
  linkHover: '#00478F',
  linkActive: '#002142',
  secondaryHover: '#E0F0FF',
  secondaryActive:'#C2E0FF',
  tertiaryHover: '#E8E8E8',
  tertiaryActive: 'D1D1D1',
  focusRing: '#009ADB',
  // GREYSCALE
  greyscale5: '#F2F2F2',
  greyscale20: '#CCCCCC',
  greyscale40: '#999999',
  greyscale60: '#666666',
  greyscale70: '#4D4D4D',
  // ACCENT
  lightGold: '#F0E7CC',
  gold: '#CBA52E',
  darkGold: '#86743D',  
  lightYellow: '#F8E5C3',
  yellow: '#FCAF17',
  darkYellow: '#8A600D',
  lightTaupe: '#EBE7DB',
  taupe: '#C1B28F',
  darkTaupe: '#7B725C',
  lightGreen: '#D1EFD4',
  green: '#39B54A',
  darkGreen: '#2B8737',
  lightLime: '#DDEDC7',
  lime: '#8DC63F',
  darkLime: '#5F8129',
  lightTeal: '#CFEDED',
  teal: '#49A7A2',
  darkTeal: '#367A76',
  lightSky: '#C5EEFA',
  sky: '#00B2E3',
  darkSky: '#1080A6',
  lightBlue: '#DBE9F5',
  blue: '#3193CC',
  darkBlue: '#0369ac',
  lightPurple: '#F1E3F2',
  purple: '#B975B7',
  darkPurple: '#92278F',
  lightOrange: '#FEE1D9',
  orange: '#F15A22',
  darkOrange: '#C64A1C',
  lightRed: '#FFE0E2',
  red: '#F0454B',
  darkRed: '#D81A21',
  lightMagenta: '#FEDFF0',
  magenta: '#F03093',
  darkMagenta: '#C00264',
  // ALERTS
  alertErrorBackground: '#FCEFF0',
  alertSuccessBackground: '#E5F0E9',
  alertInfoBackground: '#DFF3F3'

};

const theme = {
  colors: {
    mainBackground: palette.lime,
    overlayBackground: palette.systemWhite,
    overlayBodyText: palette.systemBlack,
    fadedBackground: palette.greyscale20,
    bodyText: palette.systemBlack,
    bodyTextFaded: palette.greyscale20,
    bodyTextSubdued: palette.greyscale40,
    statusSuccess: palette.success,
    successBackground: palette.alertSuccessBackground,
    successBorder: palette.darkGreen,
    statusError: palette.red,
    errorBackground: palette.alertErrorBackground,
    errorText: palette.systemBlack,
    errorBorder: palette.alert,
    infoBlockBrightBackground: palette.alertInfoBackground,
    infoBlockBrightText: palette.systemBlack,
    infoBlockNeutralBackground: palette.greyscale5,
    infoBlockNeutralText: palette.systemBlack,
    infoBlockBlackBackground: palette.systemBlack,
    infoBlockBlackText: palette.systemBlack,
    infoBlockYellowBackground: palette.warning,
    infoBlockBorder: palette.darkSky,
    divider: palette.greyscale20,
    hollowBtnColor: palette.systemWhite,
    secondaryBtnBorder: palette.link
  },
  spacing: {
    /* eslint-disable id-length */
    xs: 6,
    s: 8,
    m: 16,
    l: 24,
    xl: 32,
    xxl: 43,
    '-s': -8,
    '-m': -16,
    '-l': -24,
    '-xl': -32,
    '-xxl': -43,
    none: 0,
    /* eslint-enable id-length */
  },
  breakpoints: {
    phone: 0,
  },
  textVariants: {
    bulletText: {
      fontFamily: 'Raleway',
      fontSize: 26,
      lineHeight: 30,
    },
    smallText: {
      fontFamily: 'Raleway',
      fontSize: 14,
      lineHeight: 22,
    },
    bodyText: {
      fontFamily: 'Raleway',
      fontSize: 18,
      lineHeight: 24,
    },
    bodySubTitle: {
      fontFamily: 'Raleway-Bold',
      fontSize: 18,
      lineHeight: 24,
    },
    bodyTitle: {
      fontFamily: 'Raleway-Bold',
      fontSize: 24,
      lineHeight: 28,
    },
    overlayTitle: {
      fontFamily: 'Raleway',
      fontSize: 18,
      lineHeight: 22,
    },
    alertTitle: {
      fontFamily: 'Raleway-Bold',
      fontSize: 23,
      lineHeight: 32,
    },
    homeHeader: {
      fontFamily: 'Raleway-Bold',
      fontSize: 16,
      lineHeight: 22,
    },
    codeInput: {
      fontFamily: 'Raleway',
      fontSize: 26,
      lineHeight: 28,
    },
    menuItemTitle: {
      fontFamily: 'Raleway',
      fontSize: 16,
      lineHeight: 22,
    },
    menuItemSubtitle: {
      fontFamily: 'Raleway',
      fontSize: 12,
      lineHeight: 16,
    },
  },
  buttonVariants: {
    blackText: {
      color: 'transparent',
      height: 44,
      textColor: palette.systemBlack,
      fontFamily: 'Raleway',
      fontSize: 18,
      borderWidth: undefined,
      disabled: {},
    },
    bigFlat: {
      color: palette.link,
      height: 52,
      textColor: palette.systemWhite,
      fontFamily: 'Raleway',
      fontSize: 18,
      borderWidth: undefined,
      disabled: {
        color: palette.greyscale60,
        textColor: palette.systemBlack,
      },
    },
    bigFlatWhite: {
      color: palette.systemWhite,
      height: 52,
      textColor: palette.link,
      fontFamily: 'Raleway',
      fontSize: 18,
      borderWidth: 2,
      disabled: {},
    },
    hollow: {
      color: 'transparent',
      height: 44,
      textColor: palette.systemWhite,
      fontFamily: 'Raleway',
      fontSize: 18,
      borderWidth: 2,
      disabled: {},
    },
    bigHollow: {
      color: 'transparent',
      height: 52,
      textColor: palette.systemWhite,
      fontFamily: 'Raleway',
      fontSize: 18,
      borderWidth: 2,
      disabled: {},
    },
    smallText: {
      color: 'transparent',
      height: 24,
      textColor: palette.link,
      fontFamily: 'Raleway',
      fontSize: 16,
      borderWidth: undefined,
      disabled: {},
    },
    text: {
      color: 'transparent',
      height: 44,
      textColor: palette.link,
      fontFamily: 'Raleway',
      fontSize: 18,
      borderWidth: undefined,
      disabled: {},
    },
    subduedText: {
      color: 'transparent',
      height: 44,
      textColor: palette.greyscale40,
      fontFamily: 'Raleway',
      fontSize: 18,
      borderWidth: undefined,
      disabled: {},
    },
  },
  maxContentWidth: 500,
};

export type Theme = typeof theme;
export default theme;
